// constants/tags.ts
// Lista alfabética (ignorando mayúsculas/acentos para el orden)
export const TAGS = [
    'Agenda',
    'Alevines',
    'Alertas biológicas',
    'Alimentadores',
    'Alimento',
    'Alimento vivo',
    'Anzuelo',
    'Artes de pesca',
    'Archivos',
    'Barcos',
    'Bases de datos',
    'Becas',
    'Biofloc',
    'Bitácoras',
    'Bolsa de trabajo',
    'Boyas',
    'Cambio climático',
    'Calidad de agua',
    'Capacitación',
    'Certificaciones',
    'Clima',
    'Compartir saberes',
    'Compras',
    'Computación',
    'Comunicación social',
    'Congreso',
    'Cursos',
    'Daño ecológico',
    'Denuncias',
    'Diagnóstico',
    'Difusión',
    'Divulgación',
    'Donación',
    'Drones',
    'Economía',
    'Educación',
    'Embarcaciones',
    'Empaque',
    'Emprendedurismo',
    'Engorda',
    'Encuestas',
    'Energía',
    'Enfermedades',
    'Filtración',
    'Fisiología',
    'Fondos',
    'Foro',
    'Fotografías',
    'Genómica',
    'Gestión',
    'Guías',
    'Historia',
    'Histología',
    'Huevo',
    'Identificación de especies',
    'Impacto ambiental',
    'Inmunoestimulantes',
    'Instrumentación',
    'Inteligencia artificial',
    'Islas',
    'Laboratorios de diagnóstico',
    'Larvas de peces',
    'Larvario',
    'Licenciaturas',
    'Liderazgo',
    'Limpieza',
    'Lluvia de ideas',
    'Mareas',
    'Mercado',
    'Mentorías',
    'Meteorología',
    'Microscopia',
    'Modelos',
    'Monitoreo submarino',
    'Motores',
    'Nutrición',
    'Olas',
    'Pangas',
    'Participación',
    'Patrocinio',
    'PCR',
    'Plataforma digital',
    'Pláticas',
    'Posgrados',
    'Postlarvas',
    'Predicción',
    'Presentaciones de venta',
    'Probióticos',
    'Procesamiento',
    'Productos y servicios',
    'Promoción',
    'Protección social',
    'Proyectos',
    'Puertos',
    'Recetas',
    'Reconocimientos',
    'Recursos',
    'Redes',
    'Reproducción',
    'Reproductores',
    'Reportes',
    'Robótica',
    'Saberes tradicionales',
    'Satélites',
    'Secuenciación',
    'Sellos',
    'Sistemas',
    'Software',
    'Tecnología',
    'Talleres',
    'Toma de decisiones',
    'Trámites',
    'Transcriptómica',
    'Tratamientos',
    'Trazabilidad',
    'Turismo',
    'Vacunas',
    'ventanilla para mujeres',
    'Ventas',
    'Vigilancia ambiental'
  ] as const;
  
  export type Tag = (typeof TAGS)[number];
  